[project]
name = "titan-cli"
type = "generic"

[plugins.git]
enabled = true

[plugins.git.config]
main_branch = "master"
default_remote = "origin"

[plugins.github]
enabled = true

[plugins.github.config]
repo_owner = "masmovil"
repo_name = "titan-cli"
default_branch = "master"
pr_template_path = ".github/pull_request_template.md"
auto_assign_prs = true

[plugins.jira]
enabled = true

[plugins.jira.config]
base_url = "https://jiranext.masorange.es"
email = "alejandro.lopezr@masmovil.com"
default_project = "ECAPP"
